### PR TITLE
Ignore references to build stages when evaluating manifests

### LINKED ISSUE #24: references to previous build stages are treated as invalid manifests
This prevents applying the platform flag automatically, when it should actually be used to correctly pull multiarch base images.

eg.
```
[Warn]    Service 'balena-supervisor':
[Warn]      Multi-stage Dockerfile found with a mix of base images that require
[Warn]      CPU architecture selection and base images that do not support it.
[Warn]      The following base images do not support CPU architecture selection:
[Warn]      - build-base
[Warn]      - runtime-base
[Warn]      - runtime-base
[Warn]      The following base images require CPU architecture selection:
[Warn]      - alpine:3.11
[Warn]      - alpine:3.16
[Warn]      - debian:bullseye-slim
[Warn]      - alpine:3.16
[Warn]      As a result, the CPU architecture of the machine where the Docker Engine
[Warn]      is running will be used by default to select base images that require
[Warn]      architecture selection. This may result in incorrect architecture selection
[Warn]      and "exec format error" at runtime. It is usually possible to override the
[Warn]      architecture in the FROM line with e.g. "FROM --platform=linux/arm/v7",
[Warn]      or by adding the sha256 digest of the image for a specific architecture
```

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Resolves: https://github.com/balena-io-modules/balena-compose/issues/24

### CODE REVIEW

**Comment by klutchell** [comment]
@pipex this PR could use an automated test case or two if you can spare a few minutes

**Comment by pipex** [comment]
Sure, I'll take a look @klutchell

**Comment by pipex** [comment]
Sure, I'll take a look @klutchell

**Comment by klutchell** [comment]
Ready for review @pipex !

**Review by pipex — APPROVED** [review]
Great work!

**Pull request merged**
